package co.gov.colpensiones.beps.contracts._1_0.personas;

import javax.ejb.Local;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import co.gov.colpensiones.beps.schemas._1_0.comun.TipoInformacionContexto;
import co.gov.colpensiones.beps.schemas._1_0.personas.TipoInformacionBasicaSisben;
import co.gov.colpensiones.beps.schemas._1_0.personas.TipoInformacionPrevinculado;
import co.gov.colpensiones.beps.schemas._1_0.personas.TipoInformacionRespuestaPrevinculacion;
import co.gov.colpensiones.beps.schemas._1_0.personas.TipoRespuestaCalculoNivelSisbenDTO;

/**
 * This class was generated by Apache CXF 2.4.6 2014-06-27T15:06:55.538-05:00 Generated source version: 2.4.6
 * 
 */
@Local
@WebService(targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas", name = "ContratoSvcPrevinculado")
@XmlSeeAlso({ co.gov.colpensiones.beps.schemas._1_0.comun.ObjectFactory.class, ObjectFactory.class,
        co.gov.colpensiones.beps.schemas._1_0.personas.ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContratoSvcPrevinculado {

    /**
     * Método que calcula el nivel sisben
     * 
     * @param informacionContexto
     *            , información de contexto
     * @param datosCalculo
     *            , datos para calcular el nivel sisben
     * @return respuesta del calculo del nivel sisben
     */
    @WebResult(name = "RespuestaCalculo", targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas", partName = "RespuestaCalculo")
    @Action(input = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas/CalcularNivelSisben", output = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas/CalcularNivelSisbenResponse")
    @WebMethod(operationName = "CalcularNivelSisben", action = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas/CalcularNivelSisben")
    public TipoRespuestaCalculoNivelSisbenDTO calcularNivelSisben(
            @WebParam(partName = "InformacionContexto", name = "InformacionContexto", targetNamespace = "http://www.colpensiones.gov.co/beps/schemas/1.0/comun", header = true) TipoInformacionContexto informacionContexto,
            @WebParam(partName = "DatosCalculo", name = "DatosCalculo", targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas") TipoInformacionBasicaSisben datosCalculo);

    /**
     * Operación expuesta que permite registrar la pre-vinculación de un solicitante al programa BEPS
     * 
     * @param informacionPrevinculado
     * @return estado de la ejecución del proceso de registro
     */
    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas", partName = "EstadoEjecucion")
    @WebMethod(operationName = "Crear", action = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas/NewOperation")
    public co.gov.colpensiones.beps.schemas._1_0.comun.TipoEstadoEjecucion crear(
            @WebParam(partName = "InformacionContexto", name = "InformacionContexto", targetNamespace = "http://www.colpensiones.gov.co/beps/schemas/1.0/comun", header = true) TipoInformacionContexto informacionContexto,
            @WebParam(partName = "InformacionPrevinculado", name = "InformacionPrevinculado", targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas") TipoInformacionPrevinculado informacionPrevinculado);

    /**
     * Método encargado de resgistrar el estudio de un previnculado
     * 
     * @param informacionContexto
     *            , información del contexto
     * @param informacionResultadoPrevinculacion
     *            , información del estudio
     * @return estado de la ejecución
     */
    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas/", partName = "EstadoEjecucion")
    @WebMethod(operationName = "RegistrarResultadoEstudio", action = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas/RegistrarResultadoEstudio")
    public co.gov.colpensiones.beps.schemas._1_0.comun.TipoEstadoEjecucion registrarResultadoEstudio(
    		@WebParam(partName = "InformacionContexto", name = "InformacionContexto", targetNamespace = "http://www.colpensiones.gov.co/beps/schemas/1.0/comun", header = true) TipoInformacionContexto informacionContexto,
            @WebParam(partName = "InformacionResultadoPrevinculacion", name = "InformacionResultadoPrevinculacion", targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas/") TipoInformacionRespuestaPrevinculacion informacionResultadoPrevinculacion);

}
