package co.gov.colpensiones.beps.contracts._1_0.personas;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-06-27T15:06:55.641-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ContratoSvcPrevinculado", 
                  wsdlLocation = "file:/D:/COLP_Beps/HerramientasDesarrollo/workspaces/desarrollo_ws/generacionCodigo/wsdl/SvcPrevinculado.wsdl",
                  targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/personas") 
public class SvcPrevinculado extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.colpensiones.gov.co/beps/contracts/1.0/personas", "ContratoSvcPrevinculado");
    public final static QName EndpointPrevinculado = new QName("http://www.colpensiones.gov.co/beps/contracts/1.0/personas", "EndpointPrevinculado");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/COLP_Beps/HerramientasDesarrollo/workspaces/desarrollo_ws/generacionCodigo/wsdl/SvcPrevinculado.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SvcPrevinculado.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/COLP_Beps/HerramientasDesarrollo/workspaces/desarrollo_ws/generacionCodigo/wsdl/SvcPrevinculado.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SvcPrevinculado(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcPrevinculado(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcPrevinculado() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcPrevinculado(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcPrevinculado(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcPrevinculado(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ContratoSvcPrevinculado
     */
    @WebEndpoint(name = "EndpointPrevinculado")
    public ContratoSvcPrevinculado getEndpointPrevinculado() {
        return super.getPort(EndpointPrevinculado, ContratoSvcPrevinculado.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContratoSvcPrevinculado
     */
    @WebEndpoint(name = "EndpointPrevinculado")
    public ContratoSvcPrevinculado getEndpointPrevinculado(WebServiceFeature... features) {
        return super.getPort(EndpointPrevinculado, ContratoSvcPrevinculado.class, features);
    }

}
