package co.gov.colpensiones.contracts._1_0.pagoprestacioneseconomicas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-08-14T10:08:26.779-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas", name = "ContratoSvcNominaBeneficios")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.errores.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.tramites.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.comun.ObjectFactory.class, ObjectFactory.class, co.gov.colpensiones.schemas._1_0.personas.ObjectFactory.class, co.gov.gobiernoenlinea.gel_xml._1_0.schemas.comun.ubicacion.ObjectFactory.class, co.gov.colpensiones.schemas._1_0.pagoprestacioneseconomicas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContratoSvcNominaBeneficios {

    @WebResult(name = "InformacionCertificacionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas", partName = "InformacionCertificacionDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionDevengadosDeducidos", output = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionDevengadosDeducidosResponse")
    @WebMethod(operationName = "GenerarCertificacionDevengadosDeducidos", action = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionDevengadosDeducidos")
    public co.gov.colpensiones.schemas._1_0.personas.TipoInformacionCertificacionDTO generarCertificacionDevengadosDeducidos(
        @WebParam(partName = "CriteriosCertificacionFechaPeriodoDTO", name = "CriteriosCertificacionFechaPeriodoDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas")
        co.gov.colpensiones.schemas._1_0.pagoprestacioneseconomicas.TipoCriteriosCertificacionFechaPeriodoDTO criteriosCertificacionFechaPeriodoDTO
    );

    @WebResult(name = "InformacionCertificacionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas", partName = "InformacionCertificacionDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionExistenciaPension", output = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionExistenciaPensionResponse")
    @WebMethod(operationName = "GenerarCertificacionExistenciaPension", action = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionExistenciaPension")
    public co.gov.colpensiones.schemas._1_0.personas.TipoInformacionCertificacionDTO generarCertificacionExistenciaPension(
        @WebParam(partName = "CriteriosExistenciaPensionDTO", name = "CriteriosExistenciaPensionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas")
        co.gov.colpensiones.schemas._1_0.pagoprestacioneseconomicas.TipoCriteriosExistenciaPensionDTO criteriosExistenciaPensionDTO
    );

    @WebResult(name = "InformacionConsultaGeneralPensionadoDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas", partName = "InformacionConsultaGeneralPensionadoDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/ConsultarInformacionGeneralPensionado", output = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/ConsultarInformacionGeneralPensionadoResponse")
    @WebMethod(operationName = "ConsultarInformacionGeneralPensionado", action = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/ConsultarInformacionGeneralPensionado")
    public co.gov.colpensiones.schemas._1_0.pagoprestacioneseconomicas.TipoInformacionConsultaGeneralPensionadoDTO consultarInformacionGeneralPensionado(
        @WebParam(partName = "CriterioConsultaPensionado", name = "CriterioConsultaPensionado", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas")
        co.gov.colpensiones.schemas._1_0.pagoprestacioneseconomicas.TipoCriterioConsultaPensionado criterioConsultaPensionado
    );

    @WebResult(name = "InformacionCertificacionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas", partName = "InformacionCertificacionDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionAportesSalud", output = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionAportesSaludResponse")
    @WebMethod(operationName = "GenerarCertificacionAportesSalud", action = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas/ContratoSvcNominaBeneficios/GenerarCertificacionAportesSalud")
    public co.gov.colpensiones.schemas._1_0.personas.TipoInformacionCertificacionDTO generarCertificacionAportesSalud(
        @WebParam(partName = "CriteriosCertificacionFechaPeriodoDTO", name = "CriteriosCertificacionFechaPeriodoDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas")
        co.gov.colpensiones.schemas._1_0.pagoprestacioneseconomicas.TipoCriteriosCertificacionFechaPeriodoDTO criteriosCertificacionFechaPeriodoDTO
    );
}
