package co.gov.colpensiones.contracts._1_0.pagoprestacioneseconomicas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-08-14T10:08:26.844-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "SvcNominaBeneficios", 
                  wsdlLocation = "http://197.0.2.28:8080/COLP.Servicios.NominaBeneficios/SvcNominaBeneficios?wsdl",
                  targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas") 
public class SvcNominaBeneficios extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas", "SvcNominaBeneficios");
    public final static QName ContratoSvcNominaBeneficiosImplPort = new QName("http://www.colpensiones.gov.co/contracts/1.0/pagoprestacioneseconomicas", "ContratoSvcNominaBeneficiosImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://197.0.2.28:8080/COLP.Servicios.NominaBeneficios/SvcNominaBeneficios?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SvcNominaBeneficios.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://197.0.2.28:8080/COLP.Servicios.NominaBeneficios/SvcNominaBeneficios?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SvcNominaBeneficios(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcNominaBeneficios(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcNominaBeneficios() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcNominaBeneficios(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcNominaBeneficios(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcNominaBeneficios(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ContratoSvcNominaBeneficios
     */
    @WebEndpoint(name = "ContratoSvcNominaBeneficiosImplPort")
    public ContratoSvcNominaBeneficios getContratoSvcNominaBeneficiosImplPort() {
        return super.getPort(ContratoSvcNominaBeneficiosImplPort, ContratoSvcNominaBeneficios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContratoSvcNominaBeneficios
     */
    @WebEndpoint(name = "ContratoSvcNominaBeneficiosImplPort")
    public ContratoSvcNominaBeneficios getContratoSvcNominaBeneficiosImplPort(WebServiceFeature... features) {
        return super.getPort(ContratoSvcNominaBeneficiosImplPort, ContratoSvcNominaBeneficios.class, features);
    }

}
