package co.gov.colpensiones.contracts.afiliado.personas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-09-22T17:51:27.813-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", name = "ContratoSvcAfiliado")
@XmlSeeAlso({com.microsoft.schemas._2003.afiliado.serialization.ObjectFactory.class, co.gov.colpensiones.schemas.afiliado.comun.errores.ObjectFactory.class, co.gov.colpensiones.schemas.afiliado.comun.tramites.ObjectFactory.class, co.gov.colpensiones.schemas.afiliado.comun.ObjectFactory.class, ObjectFactory.class, co.gov.colpensiones.schemas.afiliado.personas.ObjectFactory.class, co.gov.gobiernoenlinea.gel_xml.afiliado.schemas.comun.ubicacion.ObjectFactory.class, co.gov.colpensiones.schemas.afiliado.pagoprestacioneseconomicas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContratoSvcAfiliado {

    @WebResult(name = "InformacionCertificacionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "InformacionCertificacionDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/GenerarCertificacionAfiliacion", output = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/GenerarCertificacionAfiliacionResponse")
    @WebMethod(operationName = "GenerarCertificacionAfiliacion", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/GenerarCertificacionAfiliacion")
    public co.gov.colpensiones.schemas.afiliado.personas.TipoInformacionCertificacionDTO generarCertificacionAfiliacion(
        @WebParam(partName = "CriteriosCertificacionAfiliacionDTO", name = "CriteriosCertificacionAfiliacionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas.afiliado.personas.TipoCriteriosCertificacionAfiliacionDTO criteriosCertificacionAfiliacionDTO
    );

    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "EstadoEjecucion")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/CrearRelacionLaboral", output = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/CrearRelacionLaboralResponse")
    @WebMethod(operationName = "CrearRelacionLaboral", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/CrearRelacionLaboral")
    public co.gov.colpensiones.schemas.afiliado.comun.errores.TipoEstadoEjecucion crearRelacionLaboral(
        @WebParam(partName = "InformacionRegistroRelacionLaboralDTO", name = "InformacionRegistroRelacionLaboralDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas.afiliado.personas.TipoInformacionRegistroRelacionLaboralDTO informacionRegistroRelacionLaboralDTO
    );

    @WebResult(name = "EstadoAfiliacionFondosPrivadosDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "EstadoAfiliacionFondosPrivadosDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ValidarExistenciaFondosPrivados", output = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ValidarExistenciaFondosPrivadosResponse")
    @WebMethod(operationName = "ValidarExistenciaFondosPrivados", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ValidarExistenciaFondosPrivados")
    public co.gov.colpensiones.schemas.afiliado.personas.TipoEstadoAfiliacionFondosPrivadosDTO validarExistenciaFondosPrivados(
        @WebParam(partName = "InformacionBasicaAfiliado", name = "InformacionBasicaAfiliado", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas.afiliado.personas.TipoInformacionBasicaIdentificacionPersona informacionBasicaAfiliado
    );

    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "EstadoEjecucion")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/Actualizar", output = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ActualizarResponse")
    @WebMethod(operationName = "Actualizar", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/Actualizar")
    public co.gov.colpensiones.schemas.afiliado.comun.errores.TipoEstadoEjecucion actualizar(
        @WebParam(partName = "InformacionActualizacionAfiliacionDTO", name = "InformacionActualizacionAfiliacionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas.afiliado.personas.TipoInformacionActualizacionAfiliacionDTO informacionActualizacionAfiliacionDTO
    );

    @WebResult(name = "InformacionGeneralPersonaDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "InformacionGeneralPersonaDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ConsultarInformacionGeneral", output = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ConsultarInformacionGeneralResponse")
    @WebMethod(operationName = "ConsultarInformacionGeneral", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ConsultarInformacionGeneral")
    public co.gov.colpensiones.schemas.afiliado.personas.TipoInformacionGeneralPersonaDTO consultarInformacionGeneral(
        @WebParam(partName = "IdentificacionPersona", name = "IdentificacionPersona", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas.afiliado.personas.TipoIdentificacionPersona identificacionPersona
    );

    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "EstadoEjecucion")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/Crear", output = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/CrearResponse")
    @WebMethod(operationName = "Crear", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/Crear")
    public co.gov.colpensiones.schemas.afiliado.comun.errores.TipoEstadoEjecucion crear(
        @WebParam(partName = "InformacionRegistroInicialAfiliacionDTO", name = "InformacionRegistroInicialAfiliacionDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas.afiliado.personas.TipoInformacionRegistroInicialAfiliacionDTO informacionRegistroInicialAfiliacionDTO
    );

    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas", partName = "EstadoEjecucion")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ActualizarRelacionLaboral", output = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ActualizarRelacionLaboralResponse")
    @WebMethod(operationName = "ActualizarRelacionLaboral", action = "http://www.colpensiones.gov.co/contracts/1.0/personas/ContratoSvcAfiliado/ActualizarRelacionLaboral")
    public co.gov.colpensiones.schemas.afiliado.comun.errores.TipoEstadoEjecucion actualizarRelacionLaboral(
        @WebParam(partName = "InformacionRegistroRelacionLaboralDTO", name = "InformacionRegistroActualizarRelacionLaboralDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/personas")
        co.gov.colpensiones.schemas.afiliado.personas.TipoInformacionRegistroRelacionLaboralDTO informacionRegistroRelacionLaboralDTO
    );
}
