package co.gov.colpensiones.beps.contracts._1_0.certificados;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-09-07T18:16:25.175-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ContratoSvcCertificados", 
                  wsdlLocation = "file:/D:/ambienteDesarrolloBeps/workspaceDesarrolloNuevo/CreacionWSDL/SvcCertificados.wsdl",
                  targetNamespace = "http://www.colpensiones.gov.co/beps/contracts/1.0/certificados") 
public class ContratoSvcCertificados extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.colpensiones.gov.co/beps/contracts/1.0/certificados", "ContratoSvcCertificados");
    public final static QName SvcCertificadosImplPort = new QName("http://www.colpensiones.gov.co/beps/contracts/1.0/certificados", "SvcCertificadosImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/ambienteDesarrolloBeps/workspaceDesarrolloNuevo/CreacionWSDL/SvcCertificados.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContratoSvcCertificados.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/ambienteDesarrolloBeps/workspaceDesarrolloNuevo/CreacionWSDL/SvcCertificados.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContratoSvcCertificados(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContratoSvcCertificados(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContratoSvcCertificados() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ContratoSvcCertificados(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ContratoSvcCertificados(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ContratoSvcCertificados(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SvcCertificados
     */
    @WebEndpoint(name = "SvcCertificadosImplPort")
    public SvcCertificados getSvcCertificadosImplPort() {
        return super.getPort(SvcCertificadosImplPort, SvcCertificados.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SvcCertificados
     */
    @WebEndpoint(name = "SvcCertificadosImplPort")
    public SvcCertificados getSvcCertificadosImplPort(WebServiceFeature... features) {
        return super.getPort(SvcCertificadosImplPort, SvcCertificados.class, features);
    }

}
