package co.gov.colpensiones.contracts.indicios.prestacioneseconomicas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-09-22T18:40:09.144-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas", name = "ContratoSvcIndiciosPrestaciones")
@XmlSeeAlso({co.gov.colpensiones.schemas.indicios.prestacioneseconomicas.ObjectFactory.class, com.microsoft.schemas._2003.indicios.serialization.ObjectFactory.class, co.gov.colpensiones.schemas.indicios.comun.errores.ObjectFactory.class, ObjectFactory.class, co.gov.colpensiones.schemas.indicios.comun.tramites.ObjectFactory.class, co.gov.colpensiones.schemas.indicios.comun.ObjectFactory.class, co.gov.colpensiones.schemas.indicios.personas.ObjectFactory.class, co.gov.gobiernoenlinea.gel_xml.indicios.schemas.comun.ubicacion.ObjectFactory.class, co.gov.colpensiones.schemas.indicios.pagoprestacioneseconomicas.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContratoSvcIndiciosPrestaciones {

    @WebResult(name = "InformacionConsultaGeneralCausanteDTO", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas", partName = "InformacionConsultaGeneralCausanteDTO")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas/ContratoSvcIndiciosPrestaciones/ConsultarIndiciosPensionales", output = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas/ContratoSvcIndiciosPrestaciones/ConsultarIndiciosPensionalesResponse")
    @WebMethod(operationName = "ConsultarIndiciosPensionales", action = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas/ContratoSvcIndiciosPrestaciones/ConsultarIndiciosPensionales")
    public co.gov.colpensiones.schemas.indicios.prestacioneseconomicas.TipoInformacionConsultaGeneralCausanteDTO consultarIndiciosPensionales(
        @WebParam(partName = "IdentificacionPersona", name = "IdentificacionPersona", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas")
        co.gov.colpensiones.schemas.indicios.personas.TipoIdentificacionPersona identificacionPersona
    );

    @WebResult(name = "EstadoEjecucion", targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas", partName = "EstadoEjecucion")
    @Action(input = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas/ContratoSvcIndiciosPrestaciones/RegistroInformacionPrestacion", output = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas/ContratoSvcIndiciosPrestaciones/RegistroInformacionPrestacionResponse")
    @WebMethod(operationName = "RegistroInformacionPrestacion", action = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas/ContratoSvcIndiciosPrestaciones/RegistroInformacionPrestacion")
    public co.gov.colpensiones.schemas.indicios.comun.errores.TipoEstadoEjecucion registroInformacionPrestacion();
}
