package co.gov.colpensiones.contracts.indicios.prestacioneseconomicas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-09-22T18:40:09.158-05:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "SvcIndiciosPrestaciones", 
                  wsdlLocation = "http://10.130.70.26:8230/COLP.Servicios.PrestacionesEconomicas.Indicios/SvcIndiciosPrestaciones?wsdl",
                  targetNamespace = "http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas") 
public class SvcIndiciosPrestaciones extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas", "SvcIndiciosPrestaciones");
    public final static QName ContratoSvcIndiciosPrestacionesImplPort = new QName("http://www.colpensiones.gov.co/contracts/1.0/prestacioneseconomicas", "ContratoSvcIndiciosPrestacionesImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.130.70.26:8230/COLP.Servicios.PrestacionesEconomicas.Indicios/SvcIndiciosPrestaciones?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SvcIndiciosPrestaciones.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.130.70.26:8230/COLP.Servicios.PrestacionesEconomicas.Indicios/SvcIndiciosPrestaciones?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SvcIndiciosPrestaciones(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcIndiciosPrestaciones(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcIndiciosPrestaciones() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcIndiciosPrestaciones(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcIndiciosPrestaciones(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SvcIndiciosPrestaciones(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ContratoSvcIndiciosPrestaciones
     */
    @WebEndpoint(name = "ContratoSvcIndiciosPrestacionesImplPort")
    public ContratoSvcIndiciosPrestaciones getContratoSvcIndiciosPrestacionesImplPort() {
        return super.getPort(ContratoSvcIndiciosPrestacionesImplPort, ContratoSvcIndiciosPrestaciones.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContratoSvcIndiciosPrestaciones
     */
    @WebEndpoint(name = "ContratoSvcIndiciosPrestacionesImplPort")
    public ContratoSvcIndiciosPrestaciones getContratoSvcIndiciosPrestacionesImplPort(WebServiceFeature... features) {
        return super.getPort(ContratoSvcIndiciosPrestacionesImplPort, ContratoSvcIndiciosPrestaciones.class, features);
    }

}
